sidebar:
  en:
    - label: 'Home'
      link: '/'
  
    - label: 'Getting started'
      link: '/en/intro'
      items:
        - label: 'Install'
          link: '/en/installation'
        - label: 'First Steps'
          link: '/en/first-steps'
        - label: 'Sidebar links'
          link: '/en/sidebar'

    - label: 'Extending'
      items:
        - label: 'Appearance'
          link: '/en/appearance'
        - label: 'Components'
          link: '/en/components'

  pt:
    - label: 'Início'
      link: '/'
    
    - label: 'Introdução'
      link: '/pt/intro'
      items:
        - label: 'Instalação'
          link: '/pt/instalacao'
        - label: 'Primeiros Passos'
          link: '/pt/primeiros-passos'
        - label: 'Links laterais'
          link: '/pt/lateral'

    - label: 'Extendendo'
      items:
        - label: 'Aparência'
          link: '/pt/aparencia'
        - label: 'Componentes'
          link: '/pt/componentes'
